### ISSUE TITLE
Choose portable format

### ISSUE THREAD

**Issue by koppor** [xJREB/swe-research-methods#1]
The references are nice. However, they are hard to import on a reference manager. Typically, there is bibtex used. There are transformators available converting bibtex to arbitrary formats. For a quick win, one could use pandoc to convert a bib file to markdown.

Other formats are:

- I have been recommended [MODS](http://www.loc.gov/standards/mods/) - the Metadata Object Description Schema. It is actively maintained and [bibutils](https://sourceforge.net/p/bibutils/home/Bibutils/) offers conversions to/from bibtex. A short intro about MODs is provided at https://sourceforge.net/p/bibutils/home/Working%20with%20MODS/
- http://data.bibbase.org/ontology/ seems to be promising. There are also other ontologies available: https://www.w3.org/wiki/ConverterToRdf#BibTex

(Source: https://github.com/Zearin/BibTeXML/issues/1#issuecomment-196051877)

**Comment by xJREB** [comment]
Thank you for the suggestions! I was actually thinking about using something like [citation.js](https://citation.js.org/) to develop a small static site that displays the references from a `.bib` file. For now, I added such a `.bib` file and also created a Mendeley community with all references. This should make it easier to cite the references. Feel free to let me know what you think about a small static site.

**Comment by koppor** [comment]
We need an [ultimate comparison](https://ultimate-comparisons.github.io/) for that. There are surely more than 50 solutions out there to generate static web sites with BibTeX.

I would opt for using pandoc.

The other option I like is to ping some JabRef developer to work on the documentation of the html export feature. See https://github.com/JabRef/jabref/tree/master/src/main/resources/resource/layout/listrefs for a solution working since 6 years. Maybe, we should "just" update the HTML code ^^. The "secret" for each entry is in https://github.com/JabRef/jabref/blob/master/src/main/resources/resource/layout/listrefs/listrefs.layout. (I like static pages). JabRef also has "normal" HTML layout: https://github.com/JabRef/jabref/tree/master/src/main/resources/resource/layout (scroll down)

**Comment by xJREB** [comment]
The static site is live: https://xjreb.github.io/swe-research-methods
Please have a look and tell me what you think. If you think this works, I'll close this issue.

**Comment by koppor** [comment]
Looks great! Thank you for the effort spent!

![grafik](https://user-images.githubusercontent.com/1366654/75631320-1625a300-5bf2-11ea-9ce9-573e04a56277.png)
